#!/bin/bash

# get brqanch name from ref head
if ! [ -t 0 ]; then
	read -a ref
fi
IFS='/' read -ra REF <<< "{ref[2]}"
branch="${REF[2]}"

if [ $branch == "master" ]; then
	crumb=$(curl -u "jenkins:1234" -s 'http://rachel-desktop:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
	curl -u "jenkins:1234" -H $crumb -X POST http://rachel-desktop:8080/job/job1/build?delay=0sec
	if [ $? -eq 0 ]; then
		echo "*** OK"
	else
		echo "*** Error"
	fi
fi
